name: test

on:
  push:
    branches:
      - "**"
    paths:
      - "**"
      - "!/docs/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.17.0
      - name: test
        run: sbt test
